name: Android CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Unit Test
        run: ./gradlew testDebugUnitTest --no-daemon

      - name: Lint
        run: ./gradlew lintDebug --no-daemon

      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: ScanFlow-QR-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 1

